### ISSUE TITLE
Google Chrome Install Missing

### ISSUE THREAD

**Issue by r35pect** [AdamGreenhill/lazyrecon-docker#1]
Running the docker image built from source on Kali 2021.3.

Getting an error during scan 

Starting aquatone scan...
Unable to locate a valid installation of Chrome. Install Google Chrome or try specifying a valid location with the -chrome-path option.

**Comment by AdamGreenhill** [comment]
Thanks! I'll look into this. In the mean time have you tried pulling from the Docker Hub?

https://hub.docker.com/r/adamgreenhill/lazyrecon-docker

**Comment by AdamGreenhill** [comment]
Hi @r35pect , I just checked our the Docker container on Kali Linux and everything seems to be working fine. Please re-open if you have more information on the issue.
